name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Verify lib directory
      run: |
        mkdir -p lib
        # Check if LinkedIntQueue.jar exists, if not create a placeholder
        if [ ! -f lib/LinkedIntQueue.jar ]; then
          echo "Warning: LinkedIntQueue.jar not found, creating empty placeholder"
          touch lib/LinkedIntQueue.jar
        fi
    
    - name: Build with Maven
      run: mvn -B package
    
    - name: Run tests and generate coverage report
      run: mvn test jacoco:report
    
    - name: Generate site with test and coverage reports
      run: mvn site
    
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/site/
        retention-days: 7
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: target/*.jar
        retention-days: 7
    
    - name: Archive coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: target/site/jacoco/
        retention-days: 7