name: Java Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Debug - List directory structure
      run: |
        echo "Current working directory:"
        pwd
        echo "Root directory contents:"
        ls -la
    
    - name: Create Maven project structure
      run: |
        # Create project structure
        mkdir -p src/main/java/com/example
        mkdir -p src/test/java/com/example
        
        # Create pom.xml file
        cat > pom.xml << 'EOL'
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.example</groupId>
            <artifactId>my-project</artifactId>
            <version>1.0-SNAPSHOT</version>
            <properties>
                <maven.compiler.source>17</maven.compiler.source>
                <maven.compiler.target>17</maven.compiler.target>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                    <version>4.13.2</version>
                    <scope>test</scope>
                </dependency>
            </dependencies>
        </project>
        EOL
        
        # Create Java source file
        cat > src/main/java/com/example/App.java << 'EOL'
        package com.example;
        
        public class App {
            public static void main(String[] args) {
                System.out.println("Hello World!");
            }
            
            public static String getGreeting() {
                return "Hello World!";
            }
        }
        EOL
        
        # Create test file
        cat > src/test/java/com/example/AppTest.java << 'EOL'
        package com.example;
        
        import static org.junit.Assert.assertEquals;
        import org.junit.Test;
        
        public class AppTest {
            @Test
            public void testApp() {
                assertEquals("Hello World!", App.getGreeting());
            }
        }
        EOL
        
        # Show created files
        echo "Project structure created:"
        find . -type f -not -path "*/\.*" | sort
    
    - name: Build with Maven
      run: mvn -B package
    
    - name: Run tests
      run: mvn -B test
