name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Create Maven project structure
      run: |
        # Create directories and files as seen in your workflow
        mkdir -p src/main/java/com/example
        mkdir -p src/test/java/com/example
        
        # Create main App.java file
        cat > src/main/java/com/example/App.java << 'EOL'
        package com.example;
        
        public class App {
            public static String getGreeting() {
                return "Hello World!";
            }
        }
        EOL
        
        # Create test file
        cat > src/test/java/com/example/AppTest.java << 'EOL'
        package com.example;
        
        import static org.junit.Assert.assertEquals;
        import org.junit.Test;
        
        public class AppTest {
            @Test
            public void testApp() {
                assertEquals("Hello World!", App.getGreeting());
            }
        }
        EOL
    
    - name: Generate pom.xml
      run: |
        cat > pom.xml << 'EOL'
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" 
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            
            <groupId>com.example</groupId>
            <artifactId>example-project</artifactId>
            <version>1.0-SNAPSHOT</version>
            
            <properties>
                <maven.compiler.source>11</maven.compiler.source>
                <maven.compiler.target>11</maven.compiler.target>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            </properties>
            
            <dependencies>
                <dependency>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                    <version>4.13.2</version>
                    <scope>test</scope>
                </dependency>
            </dependencies>
            
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>3.1.2</version>
                    </plugin>
                </plugins>
            </build>
        </project>
        EOL
    
    - name: Build with Maven
      run: mvn -B package
    
    - name: Run tests
      run: mvn test
    
    - name: Show created files
      run: find . -type f -not -path "*/\.*" | sort
    
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports/
        retention-days: 7
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: target/*.jar
        retention-days: 7